print("CASH RECEIPT")
print("------------------------------")
print("Charged to____________________")
print("Received by___________________")
print("------------------------------")
print("\u00A9 SoftUni")
